### ISSUE TITLE
Create additional location related features for investments predictions dataset

### ISSUE THREAD

**Issue by Jack-0-0** [nestauk/innovation_sweet_spots#137]
It would be good to create additional location related features for the investments predictions dataset using data from the [BEIS indicators](https://github.com/nestauk/beis-indicators).

This would require matching Crunchbase location information with the regions used in the BEIS indicators.

The BEIS data uses locations in either NUTS2, NUTS3 or LEP structure.

Currently the investment predctions dataset is using `location_id` from Crunchbase for each company. This is in the format city_country, for example `oxford_united-kingdom`.

We could use a different Crunchbase location variable if it is easier to join to the BEIS data.   In Crunchbase there is postcode but that is missing for about a third of the companies.

From a quick first look it seems that the Crunchbase `location_id` variable is potentially at too low of a level. It may be better to use the Crunchbase variable `region`. The `region` variable seems to have the value `England` when it should be `London` so it could make sense to reassign `England` to `London`.

To download the BEIS data you can access it either on [ Github](https://github.com/nestauk/beis-indicators/tree/dev/ds/data/processed) or from the [government website](https://access-research-development-spatial-data.beis.gov.uk/indicators) (click download on the top right).

**Comment by beingkk** [comment]
Thanks @Jack-0-0 for the suggestions!

I had a first go at this, and looks like the following pipeline could work:

- **Step 1**: Find latitude and longitude of each CB company
  - Using postcodes (about 100k companies)
  - Locating all companies with a generic "London, England, United Kingdom" address to one code (a few 10s of thousands)
  - The rest (about 30k) with non-generic addresses but incomplete or missing postcodes, locate using Microsoft Bing API
- **Step 2**: Map latitude and longitude to NUTS (eg, using nuts-finder package)
- **Step 3**: For each BEIS indicator of interest, find the most recent year and map to the companies via NUTS. Here I guess some care needs to be taken to use the right NUTS code (as the codes I guess might change between different versions).

I will aim to finish the issue some time next week.
