### ISSUE TITLE
make install errors

### ISSUE THREAD

**Issue by jaklinger** [nestauk/innovation_sweet_spots#16]
First time usage I get the following three errors on `make install`. I can fix the first two, but the third requires some deeper digging

## 1: `Makefile:14: .env: No such file or directory`

Which can be remedied by creating `.env`, but probably should have some logic creates if it doesn't exist (i.e. `touch .env`)

## 2: `innovation_sweet_spots setup command: 'install_requires` ... `Parse error at "'+https:/'": Expected stringEnd`

After fixing the above I run into

```
make install
conda env create -q -n innovation_sweet_spots -f environment.yaml
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
/Library/Developer/CommandLineTools/usr/bin/make -s pip-install
    ERROR: Command errored out with exit status 1:
     command: /Users/jklinger/anaconda3/envs/innovation_sweet_spots/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/jklinger/Nesta/innovation_sweet_spots/setup.py'"'"'; __file__='"'"'/Users/jklinger/Nesta/innovation_sweet_spots/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/zc/xq14ps8175s62kfvt2_2r649xlpw4k/T/pip-pip-egg-info-4nsh16pl
         cwd: /Users/jklinger/Nesta/innovation_sweet_spots/
    Complete output (1 lines):
    error in innovation_sweet_spots setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Parse error at "'+https:/'": Expected stringEnd
    ----------------------------------------
WARNING: Discarding file:///Users/jklinger/Nesta/innovation_sweet_spots. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
make[1]: *** [pip-install] Error 1
make: *** [conda-create] Error 2
```

which requires changing `git+https://github.com/nestauk/data_getters.git` to `data_getters @ git+https://github.com/nestauk/data_getters.git` in `requirements.txt`

## 3. `make install` Hangs (recursive lookup?)

After the above fixes, the install instead hangs indefinitely (> 10 mins). I killed the command, which gives the following stack trace, indicating that there is a recursive lookup in the `pip-install` section of the Makefile

```
Traceback (most recent call last):
  File "/Users/jklinger/anaconda3/envs/innovation_sweet_spots/lib/python3.7/contextlib.py", line 509, in __exit__
    if cb(*exc_details):
  File "/Users/jklinger/anaconda3/envs/innovation_sweet_spots/lib/python3.7/contextlib.py", line 377, in _exit_wrapper
    return cm_exit(cm, exc_type, exc, tb)
  File "/Users/jklinger/anaconda3/envs/innovation_sweet_spots/lib/python3.7/site-packages/pip/_internal/utils/temp_dir.py", line 165, in __exit__
    self.cleanup()
  File "/Users/jklinger/anaconda3/envs/innovation_sweet_spots/lib/python3.7/site-packages/pip/_internal/utils/temp_dir.py", line 184, in cleanup
    rmtree(self._path)
  File "/Users/jklinger/anaconda3/envs/innovation_sweet_spots/lib/python3.7/site-packages/pip/_vendor/tenacity/__init__.py", line 339, in wrapped_f
    return self(f, *args, **kw)
  File "/Users/jklinger/anaconda3/envs/innovation_sweet_spots/lib/python3.7/site-packages/pip/_vendor/tenacity/__init__.py", line 430, in __call__
    do = self.iter(retry_state=retry_state)
  File "/Users/jklinger/anaconda3/envs/innovation_sweet_spots/lib/python3.7/site-packages/pip/_vendor/tenacity/__init__.py", line 367, in iter
    return fut.result()
  File "/Users/jklinger/anaconda3/envs/innovation_sweet_spots/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/Users/jklinger/anaconda3/envs/innovation_sweet_spots/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/Users/jklinger/anaconda3/envs/innovation_sweet_spots/lib/python3.7/site-packages/pip/_vendor/tenacity/__init__.py", line 433, in __call__
    result = fn(*args, **kwargs)
  File "/Users/jklinger/anaconda3/envs/innovation_sweet_spots/lib/python3.7/site-packages/pip/_internal/utils/misc.py", line 135, in rmtree
    shutil.rmtree(dir, ignore_errors=ignore_errors, onerror=rmtree_errorhandler)
  File "/Users/jklinger/anaconda3/envs/innovation_sweet_spots/lib/python3.7/shutil.py", line 496, in rmtree
    os.rmdir(path)
KeyboardInterrupt
make[1]: *** [pip-install] Error 1
make: *** [conda-create] Interrupt: 2
```

**Comment by beingkk** [comment]
Uff, apologies for having to go through this - I should have checked it before!!

### Some deeper digging...
The third issue was caused by the installation of the `data_getters` package (when the requirement for `data_getters` was removed, `make install` worked fine).

Looks like it was downloading every previous version of a package, see below:

```shell
...
  Downloading awscli-1.19.16-py2.py3-none-any.whl (3.6 MB)
     |████████████████████████████████| 3.6 MB 12.4 MB/s 
  Downloading awscli-1.19.15-py2.py3-none-any.whl (3.6 MB)
     |████████████████████████████████| 3.6 MB 9.5 MB/s 
  Downloading awscli-1.19.14-py2.py3-none-any.whl (3.6 MB)
     |████████████████████████████████| 3.6 MB 21.2 MB/s 
  Downloading awscli-1.19.13-py2.py3-none-any.whl (3.6 MB)
     |████████████████████████████████| 3.6 MB 17.7 MB/s 
  Downloading awscli-1.19.12-py2.py3-none-any.whl (3.6 MB)
     |████████████████████████████████| 3.6 MB 22.2 MB/s 
  Downloading awscli-1.19.11-py2.py3-none-any.whl (3.6 MB)
     |████████████████████████████████| 3.6 MB 1.1 MB/s 
  Downloading awscli-1.19.10-py2.py3-none-any.whl (3.6 MB)
     |████████████████████████████████| 3.6 MB 11.4 MB/s 
  Downloading awscli-1.19.9-py2.py3-none-any.whl (3.6 MB)
     |████████████████████████████████| 3.6 MB 25.7 MB/s 
  Downloading awscli-1.19.8-py2.py3-none-any.whl (3.6 MB)
     |██████████████████████▋         | 2.5 MB 31.3 MB/s eta 0:00:01^C
ERROR: Operation cancelled by user
make[1]: *** [pip-install] Error 1
make: *** [conda-create] Interrupt: 2
```

Not sure why exactly this happens (maybe related to [this](https://serverfault.com/questions/1046683/pip-upgrade-downloading-every-previous-version-until-storage-is-full), but I had the same problem even after updating `pip`)

Interestingly, this behaviour doesn't happen when executing the commands `pip install -r requirements.txt` and `pip install -r requirements_dev.txt`, in this order. Conversely, if I do `pip install -r requirements.txt -r requirements_dev.txt` (i.e. both requirements in the same line), I get the same problem. So, I guess it some kind of pip dependency hell?

### Solution 
So, for the time being, I will adjust the recipe for the `pip-install` target to install the packages using the `-r` option, in the specified order, i.e.
```shell
pip-install:
	# $(call execute_in_env, pip install -e ".[dev]")
	$(call execute_in_env, pip install -r requirements.txt)
	$(call execute_in_env, pip install -r requirements_dev.txt)
	$(call execute_in_env, pip install -e .)
```

### However...
It still throws out some pip dependency resolver errors, but not sure how serious that is, as the installation completes. I think the reason for the dependency resolver errors are the versions required by nesta [monorepo](https://github.com/nestauk/nesta/blob/291_glass_ai/requirements.txt).

```shell
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
black 21.5b1 requires click>=7.1.2, but you have click 7.0 which is incompatible.
awscli 1.19.82 requires botocore==1.20.82, but you have botocore 1.12.205 which is incompatible.
awscli 1.19.82 requires s3transfer<0.5.0,>=0.4.0, but you have s3transfer 0.2.1 which is incompatible.
```

**Comment by beingkk** [comment]
By the way, would you suggest removing the "editable" option (i.e. the `pip install -e .` call), as it's suggested for the `ojd_daps` project?

**Comment by jaklinger** [comment]
nice, i'll check out the fix once it's in!

> By the way, would you suggest removing the "editable" option (i.e. the `pip install -e .` call), as it's suggested for the `ojd_daps` project?

I would say that `-e` is useful if you envisage yourself using the repo as a dependency elsewhere, since it symlinks the current repo `innovation_sweet_spots` into `site-packages`, meaning that changes in `innovation_sweet_spots` are reflected immediately if you're doing `from innovation_sweet_spots import something` in another repo. Otherwise, you can ditch it!

> It still throws out some pip dependency resolver errors, but not sure how serious that is, as the installation completes. I think the reason for the dependency resolver errors are the versions required by nesta monorepo.

It basically because of `boto3` which has a horrific set of pinned dependencies, sigh
