### ISSUE TITLE
Split GtR research funding across duration of the project

### ISSUE THREAD

**Issue by Jack-0-0** [nestauk/innovation_sweet_spots#88]
The GtR time series data at `innovation_sweet_spots/outputs/finals/pilot_outputs/time_series' currently attributes all research funding to the date that the funding was awarded.

It would be useful to add in functionality to split the funding equally across the length of the project.

**Comment by beingkk** [comment]
Hey @Jack-0-0 , just to clarify from our previous chat, I think it might be useful to:
- use the `GtrWrangler.get_funding_data` from [here](https://github.com/nestauk/innovation_sweet_spots/issues/88) to fetch funding data
- write a function that splits the funding uniformly across the duration of the project (probably makes sense to have this function in wrangling_utils?)
- if your time resolution is `year` then I think you should be able to produce time series using `gtr_funding_per_year` from the[ analysis utils](https://github.com/nestauk/innovation_sweet_spots/blob/dev/innovation_sweet_spots/analysis/analysis_utils.py) without any modifications...
